unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g prefix C-s
set-option -g repeat-time 100
set-option -g focus-events on

# Fix escape time for Neovim
set -sg escape-time 0

# UTF-8 Locale Support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set -g mouse on

# Window naming configuration - KEEP IT SIMPLE
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# --- NAVIGATION (Vim-Tmux-Navigator handled by plugin) ---
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Kill panes
bind -r e kill-pane -a

# --- RESIZE PANES ---
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# --- COPY MODE ---
set -s set-clipboard on
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel



# --- COLORS, THEME & STATUSLINE ---
source-file ~/.config/tmux/colors.conf
source-file ~/.config/tmux/theme.conf
source-file ~/.config/tmux/statusline.conf

# --- UTILITIES ---
source-file ~/.config/tmux/utility.conf

# --- PLUGINS ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TPM (Keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
